### ISSUE TITLE
Add a note about watchOS/tvOS support to the README

### ISSUE THREAD

**Issue by pixlwave** [getditto/rust-bitcode#14]
Hey, thanks for making this project. It might be useful to add whether watchOS and tvOS support works too?

I found the repo after searching for the possibility of running Rust code on watchOS, and *think* rust-bitcode might help with that, but not 100% sure?

Thanks 😄

**Comment by thombles** [comment]
Unfortunately all the references to "iOS" are intentional! I'll add a note to the readme to clarify, thanks.

At this time a watchOS triple hasn't been added to the Rust compiler at all, and tvOS is `no_std`-only: https://doc.rust-lang.org/nightly/rustc/platform-support.html

This is the issue for adding the new platforms: https://github.com/rust-lang/rust/issues/48862

It is definitely in scope for this project to cover those other Apple platforms. Since Apple Watches require bitcode for submission it will be pretty important to align with Xcode.

**Comment by pixlwave** [comment]
Not to worry, thanks for clarifying 😊
