### ISSUE TITLE
Add PSA to README noting that Apple no longer requires bitcode

### ISSUE THREAD

**Issue by frewsxcv** [getditto/rust-bitcode#27]
https://github.com/rust-lang/rust/issues/35968#issuecomment-1148183215

**Comment by thombles** [comment]
It's exciting news but let's not count our chickens before they hatch. I'll be happy to make some sort of announcement after we've seen:

* libraries produced by vanilla Rust toolchains working in Xcode 14 GM on physical devices
* successful deployments all the way to TestFlight or the App Store, thereby exercising all of Apple's binary analysis checks

It _should_ work just fine since the no-bitcode path has been reliable so far, but a lot can happen over the course of an Xcode beta.

**Comment by thombles** [comment]
Xcode 14 checks out - notice added to readme. 🎉
